# Generated by Django 6.0.5 on 2026-05-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0003_scorehistory_exam_title_scorehistory_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='試験名')),
                ('choice_type', models.CharField(choices=[('numeric', '1〜5'), ('alpha', 'A〜E')], default='numeric', max_length=10, verbose_name='選択肢タイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '試験',
                'verbose_name_plural': '試験一覧',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='問題番号')),
                ('text', models.TextField(verbose_name='問題文')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='正解')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='keiba_app.exam', verbose_name='試験')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題一覧',
                'ordering': ['number'],
            },
        ),
    ]
