# Generated by Django 6.0.5 on 2026-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0004_exam_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_questions',
            field=models.BooleanField(default=True, verbose_name='問題文を表示する'),
        ),
    ]
