# Generated by Django 6.0.5 on 2026-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0005_exam_show_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='memo',
            field=models.TextField(blank=True, verbose_name='詳細メモ'),
        ),
        migrations.AddField(
            model_name='exam',
            name='short_title',
            field=models.CharField(blank=True, max_length=20, verbose_name='簡略名'),
        ),
    ]
