# Generated by Django 6.0.5 on 2026-06-19 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='keiba_app.category', verbose_name='カテゴリ'),
        ),
    ]
